{{- range $key, $value := .Values }}
{{- if not (or (eq $key "application") (eq $key "environment") (eq $key "global") (eq $key "revision")) }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $key }}-record-deployment-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ $key }}-record-deployment
    spec:
      restartPolicy: Never
      containers:
      - name: post-install-job
        image: byrnedo/alpine-curl
        args: {{ include $key $.Values | nindent 10 }}
{{- end }}
{{- end }}
